apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: go-firebase-app
  name: go-firebase-app
spec:
  replicas: 1
  selector:
    matchLabels:
      run: go-firebase-app
  template:
    metadata:
      labels:
        run: go-firebase-app
    spec:
      containers:
      - image: gcr.io/elegant-zodiac-264511/go-firebase-app
        name: go-firebase-app
        env:
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: /cred/elegant-zodiac-264511-firebase-adminsdk-hsgen-6db742a60c.json
        volumeMounts:
          - name: firebase-credential
            mountPath: "/cred/"
      volumes:
        - name: firebase-credential
          secret:
            secretName: firebase-adminsdk