apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: go-firebase-app
  name: go-firebase-app
spec:
  replicas: 1
  selector:
    matchLabels:
      run: go-firebase-app
  template:
    metadata:
      labels:
        run: go-firebase-app
    spec:
      containers:
      - image: gcr.io/elegant-zodiac-264511/go-firebase-app
        name: go-firebase-app
