apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: go-firebase-app
  name: go-firebase-app
spec:
  replicas: 1
  selector:
    matchLabels:
      run: go-firebase-app
  template:
    metadata:
      labels:
        run: go-firebase-app
    spec:
      containers:
      - image: gcr.io/elegant-zodiac-264511/go-firebase-app
        name: go-firebase-app
        env:
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: /cred/elegant-zodiac-264511-firebase-adminsdk-hsgen-6db742a60c.json
        envFrom:
        - secretRef:
            name: postgres-connection
        volumeMounts:
          - name: firebase-credential
            mountPath: "/cred/"
      - name: cloudsql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.14
        command: ["/cloud_sql_proxy",
                "-instances=elegant-zodiac-264511:us-central1:sample-postgres=tcp:5432",
                # If running on a VPC, the Cloud SQL proxy can connect via Private IP. See:
                # https://cloud.google.com/sql/docs/mysql/private-ip for more info.
                "-ip_address_types=PRIVATE",
                "-credential_file=/secrets/cloudsql/elegant-zodiac-264511-98b4cbf582b8.json"]
        securityContext:
          runAsUser: 2  # non-root user
          allowPrivilegeEscalation: false
        volumeMounts:
          - name: cloudsql-instance-credentials
            mountPath: /secrets/cloudsql
            readOnly: true
      volumes:
        - name: firebase-credential
          secret:
            secretName: firebase-adminsdk
        - name: cloudsql-instance-credentials
          secret:
            secretName: cloudsql-instance-credentials