apiVersion: v1
kind: Service
metadata:
  labels:
    run: go-firebase-app
  name: go-firebase-app-svc
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    run: go-firebase-app
  type: ClusterIP
